services:
  card-database:
    image: postgres:15-alpine
    container_name: card-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=card-database
    ports:
      - 7432:5432
    volumes:
      - card-database-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  card-database-data:
